### ISSUE TITLE
Make Gemfile include looser version number specification

### ISSUE THREAD

**Issue by albertyw** [launchdarkly/hello-ruby#2]
The Gemfile in this repo contains the line https://github.com/launchdarkly/hello-ruby/blob/master/Gemfile#L5 which has a hardcoded version number.  I'd recommend that the version number here (and in customer repositories) be `gem 'ldclient-rb', '~> 0.4.0'` or `gem 'ldclient-rb', '~> 0.4'` assuming the gem follows semantic versioning (http://semver.org/) so that customers' gems can be easily updated.  (`gem 'ldclient-rb', '~> 0.4.0'` means any gem with a version [0.4.0, 0.5.0) is allowed)

Also, having a hardcoded version number here would require this repo to be updated with every single new gem update.

**Comment by jkodumal** [comment]
Done-- thanks.
